### PR TITLE
.NET6 Upgrade

### PR DESCRIPTION
**Pull request by CaptnCodr**
This PR updates the projects to .NET6 including Nuget packages.

### CODE REVIEW

**Comment by CaptnCodr** [comment]
@grahamrhay @Lashas83 
I wanted to remind you to review this and maybe merge this huge upgrade.

Thank you.

**Comment by grahamrhay** [comment]
I have long since exited dotnet land, I'm afraid. I've added you to the org, can you merge it? I have no idea what permissions are default. And I'm not sure who is currently in control of the nuget creds either.

**Comment by CaptnCodr** [comment]
Yes, I could merge it. 
But I don't know about the Nuget package deployment.

**Comment by CaptnCodr** [comment]
Yes, CaptnCodr is my username there aswell.

**Comment by CaptnCodr** [comment]
@grahamrhay Thank you for this opportunity!

**Pull request merged**
